---
- slug: something-local
  display_name: Something Local
  items:
    - cocktail_slug: esmeralda
    - cocktail_slug: mai-tai
      spec_slug: state-park
    - cocktail_slug: queen-christina
    - cocktail_slug: ce-soir
    - cocktail_slug: adelita
    - cocktail_slug: freehand-old-fashioned
